### ISSUE TITLE
REAME clarification

### ISSUE THREAD

**Issue by remrobem** [jbelmont/api-workshop#10]
The curl command needs to be run for Mac, not sure about Windows/Linux
The text for installing gometalinter need to be split into multiple lines and is for Mac (not sure if Windows/Linux have an equivalent command

Binary Releases To install the latest stable release:

curl -L https://git.io/vp6lP | sh Alternatively you can install a specific version from the releases list.

Homebrew brew tap alecthomas/homebrew-tap brew install gometalinter

**Comment by jbelmont** [comment]
Okay thank you I have updated this section.
