### ISSUE TITLE
Changes to get app to run 

### ISSUE THREAD

**Issue by remrobem** [jbelmont/api-workshop#11]
cmd/apid/config/config.go

- changed APIHost to 8008

**Comment by remrobem** [comment]
docker-compose.yml

- changed apid: ports:   to 8008:8008

Makefile

- removed web from dev:   docker-compose

**Comment by jbelmont** [comment]
@remrobem thanks for the issue I have updated this the sections with these changes now since we tested them yesterday and they work.
