### ISSUE TITLE
running make from top directory fails with dep command not found in windows 10 golang

### ISSUE THREAD

**Issue by mlisanke** [jbelmont/api-workshop#5]
D:\workspace\api-workshop>make
go get -u github.com/mattn/goveralls
go get -u github.com/philwinder/gocoverage
go get -u github.com/alecthomas/gometalinter
go get -u github.com/golang/dep/cmd/dep
go get -u golang.org/x/tools/cmd/cover
dep ensure
make: dep: Command not found
make: *** [Makefile:12: ensure] Error 127

**Comment by jbelmont** [comment]
I am going to close this issue as it is related to installing dep command which I have added to the README.md instructions now.
