### ISSUE TITLE
Once dep is setup, go requires GOPATH/src configuration</goNeophyte>

### ISSUE THREAD

**Issue by Three97** [jbelmont/api-workshop#6]
{compuerName}:{folder} {user}$ make
go get -u github.com/mattn/goveralls
go get -u github.com/philwinder/gocoverage
go get -u github.com/alecthomas/gometalinter
go get -u github.com/golang/dep/cmd/dep
go get -u golang.org/x/tools/cmd/cover
dep ensure
root project import: {fullPathToFolder} is not within any GOPATH/src
make: *** [ensure] Error 1

**Comment by jbelmont** [comment]
This is good information, and sorry for the late reply I will add it to the README.md. I added a section for  installing dep but I also need to add a section for where to put the directory path at.
